# Generated by Django 3.1.2 on 2021-07-21 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_drop'),
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=108)),
                ('img', models.ImageField(default='static/images/DIET3.jpg', upload_to='images')),
            ],
        ),
    ]
